version: 2.0
jobs:
  build:
    docker:
      - image: clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein test
      - save_cache:
          paths:
            - $HOME/.m2
          key: << checksum "project.clj" >>
